### ISSUE TITLE
Scan parent theme too if active theme is a child theme

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antivirus#1]
At the moment we just scan the active theme. If the active theme is a child theme we should scan the according parent theme too.

There are several threads in the support forums asking for the feature:
https://wordpress.org/support/topic/child-and-parent-themes
https://wordpress.org/support/topic/child-themes-17
https://wordpress.org/support/topic/testing-childthemes

Not sure if this a bug or an enhancement ;)
Let's call it an enhancement.

**Comment by glueckpress** [comment]
Users keep chiming in on this one: https://wordpress.org/support/topic/child-and-parent-themes?replies=3#post-7175200
Looks like a useful feature.
