### ISSUE TITLE
Remove fallback API key for Google SafeBrowsing API

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antivirus#104]
We are not allowed to use this API in the plugin. We are forced to use the paid Web Risk API:
https://cloud.google.com/web-risk

There seems to be a free rate, but with a public key this is to risky for me.

So we need to remove the fallback API key completely.

Looking at the test URL we could provide a direct link for testing:
https://transparencyreport.google.com/safe-browsing/search?url=example.de

And we should add a documentation to get this the Safebrowsing API key.

**Comment by stklcode** [comment]
Strictly speaking is was never really "okay" to use a shared key, I guess.

We have this option for SafeBrowsing since 1.4, so my suggestion is to
1. add a link to the Google documentation how to obtain the key
   add a hint to the "non-commercial" clause
   probably add a link to the web UI for a manual check
4. push a minor release with an admin notice that the fallback will be removed with the next point release and administrators must migrate
5. remove the fallback with 1.5 and only run the check if a key is provided
6. revoke "our" API key shortly after 1.5 has been released - remaining 1.4 instances yet generate an email notice for invalid keys

Introducing additional _Web Risk_ support would be a nice feature, too.

**Comment by Zodiac1978** [comment]
> Strictly speaking is was never really "okay" to use a shared key, I guess.

Yes.

> add a link to the Google documentation how to obtain the key

Looking at the Map API documentation, I don't think there is an easy tutorial on the Google pages for this.

> add a hint to the "non-commercial" clause

Where and why?

>  probably add a link to the web UI for a manual check

Yes, it seems to be easy to provide a link which contains the URL of the site already.

> push a minor release with an admin notice that the fallback will be removed with the next point release and administrators must migrate

We should not wait for too long with this ...

> remove the fallback with 1.5 and only run the check if a key is provided

👍

> revoke "our" API key shortly after 1.5 has been released - remaining 1.4 instances yet generate an email notice for invalid keys

What do you mean with email notice? They will get false positives or not? No email informing about invalid kex, or not?

> Introducing additional Web Risk support would be a nice feature, too.

What is the difference? I thought it is just non-commercial vs. commercial:
_"The following Safe Browsing APIs are for non-commercial use only. If you need to use APIs to detect malicious URLs for commercial purposes – meaning “for sale or revenue-generating purposes” – please refer to the Web Risk API."_

**Comment by stklcode** [comment]
> Looking at the Map API documentation, I don't think there is an easy tutorial on the Google pages for this.

Pretty straight forward in my eyes.
https://developers.google.com/safe-browsing/v4/get-started

But yes, the UI and the ACL system aren’t that intuitive for the average user.

> Yes, it seems to be easy to provide a link which contains the URL of the site already.

We already send such links along with the warning. Show it on the settings page should be no problem.

https://github.com/pluginkollektiv/antivirus/blob/b9c9afd19be2a94460a5c25345ba25d79b25f4a2/inc/class-antivirus-safebrowsing.php#L81-L87

> What do you mean with email notice? They will get false positives or not? No email informing about invalid kex, or not?

Depends on the version they use. In 1.4 we detect errors (key invalid, limit exceeded, etc.) and send such message “check failed ... provide/check your key“. Older versions will send false positives.

> > Introducing additional Web Risk support would be a nice feature, too.
> 
> What is the difference? I thought it is just non-commercial vs. commercial:

Isn‘t that enough difference?
Function and result are pretty close for our use case, both will likely give the same results and are similar to use. So it should be no problem to enable both APIs and let the uses decide for which they provide an API key. Maybe just add a select box, using both should not give any benefit.

**Comment by Zodiac1978** [comment]
> the UI and the ACL system aren’t that intuitive for the average user.

Yes, that's what I thought. Many Map plugins have their own documentation because of this.

> We already send such links along with the warning. Show it on the settings page should be no problem.

Yes. URL encode the site URL  - that's what I meant 👍 

> Depends on the version they use. 

Therefore the misunderstanding. You are complete right with this longer explanation. 

> should be no problem to enable both APIs and let the uses decide for which they provide an API key

You are right. This makes sense. In most cases the free tier should be sufficient for our use case.
