### ISSUE TITLE
Prepare 1.5.0 release

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antivirus#130]
- [x] Add new entry in _CHANGELOG.md_
- [x] Raise version number to 1.5.0 in _antivirus.php_
- [x] Raise "Tested up to:" to 6.4 in _README.md_
- [x] Raise "Stable tag:" to 1.5.0 in _README.md_
- [x] Add new entry to changelog area in _README.md_
- [x] Check for wrong or placeholder `@since` docblock entries
- [x] Update screenshots for w.org
- [x] Post a release article on https://antivirus.pluginkollektiv.org
- [ ] Toot about it with @pluginkollektiv@dewp.space

https://github.com/pluginkollektiv/antivirus/compare/v1.4.4...develop

**Comment by stklcode** [comment]
Documentation at https://antivirus.pluginkollektiv.org/documentation/ should also be checked and updated. Seems pretty outdated, but some current screenshots and a word or two about API Keys should do the job.
