### ISSUE TITLE
Rename "There is no virus" button

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/antivirus#15]
It's not clear that "There is no virus" is actually a button to dismiss the notification and not just a statement.

See https://wordpress.org/support/topic/virus-suspected-emails-received-but-no-info-on-what-the-issue-is?replies=6

![fireshot capture - antivirus edward_ - http___edwardtakespictures com_wp-admin_options-general php](https://cloud.githubusercontent.com/assets/841956/10039698/ea095080-61d4-11e5-96b1-1ed621080fdc.png)

**Comment by swissspidy** [comment]
The styling should be more WP-like

**Comment by Zodiac1978** [comment]
We renamed the button to "This is not a virus", but I will not close this issue as this still not very clear. I think it should be something more like "Mark as: not a virus" or "Dismiss" or "This is a false positive" - something that sounds more like an action item and no statement.

For the styling issue we have #22

**Comment by 00travelgirl00** [comment]
Vote for "Dismiss"! Everything else is nor clear as a action for translation.
