### ISSUE TITLE
Remove translation files

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/antivirus#17]
- Remove POT file
- Remove German translation files  
  Those are 100% translated on WordPress.org

@Zodiac1978 Can you validate my suggested translations for [de_DE_formal](https://translate.wordpress.org/locale/de/formal/wp-plugins/antivirus)? Thanks!

**Comment by Zodiac1978** [comment]
@swissspidy Your translations are approved.

**Comment by 00travelgirl00** [comment]
@Zodiac1978 can we close this ticket? german files has been removed. 

Spanisch es_ES is still included. But it is 96% translated in wordpress.org

https://translate.wordpress.org/locale/es/default/wp-plugins/antivirus
