### ISSUE TITLE
Road to 1.4.0

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/antivirus#19]
See pluginkollektiv/antispam-bee#33

**Comment by bueltge** [comment]
We should switch the minimum php version to 5.6 so that we can work easier. Currently, is hard to testing smaller than 5.6 and the quality tools has also a lot of problems to run in the old not maintained php versions.

**Comment by Zodiac1978** [comment]
> We should switch the minimum php version to 5.6 so that we can work easier.

+1
