### ISSUE TITLE
Make UI more WordPress-like

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/antivirus#22]
The user should feel at home. AntiVirus should integrate neatly into WordPress like any other plugin.

**Comment by 00travelgirl00** [comment]
I had some ideas about it and made some Mockups. I think the most WordPressy Feel would be the Layout like the Post overview or the Media Uploads view (for multiple Files). 

Also I have add Tabs, cause the Settings on the same page like the checker seems a bit confusing to me. 

In the Mockups are also some new functionanalities. (But of course they are just some ideas.)

- Check every installed Theme, not just the active one. #1
- Save Check-Status, so User can see it later as well 
- Add Information-Button to explain, why this is a potential Security Issue

Overview:
![Antivirus_mockup_Overview](https://user-images.githubusercontent.com/21318377/68595714-4823c580-049a-11ea-9fa2-544d02d1c00e.png)

Details:
![Antivirus_mockup_Details](https://user-images.githubusercontent.com/21318377/68595721-4b1eb600-049a-11ea-930e-c72484d54bc4.png)
