### ISSUE TITLE
Update checks to detect more malicious code

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/antivirus#23]
Core ticket [#37444](https://core.trac.wordpress.org/ticket/37444) mentions a file `wp-includes/theme-compat/category.php` file with malicious code in it. It would be great if we could somehow detect such stuff too.

**Comment by Zodiac1978** [comment]
This is the code @swissspidy was mentioning:
```

Reported by: | crs1138 | Owned by: |  
-- | -- | -- | --
  | normal
normal | 4.5.3
Themes |  
template |  
```

**Comment by Zodiac1978** [comment]
I o not see an easy fix here. The chunks are to small. If we check for them the risk is high that we get false positives. And many variable names are normal words (e.g. "$benchmark")

**Comment by 2ndkauboy** [comment]
How about running the "verify-checksums" command of the WP CLI (if installed) and check for modified core, theme and plugin files?

**Comment by Zodiac1978** [comment]
Looks more like something we should discuss in #5 or #24 as a summary issue for new approaches.

**Comment by Zodiac1978** [comment]
This ticket seems to be unsolvable. As nobody has an idea to solve this for about four years, I am closing this now.
