### ISSUE TITLE
Make "Email Label" A11y

### ISSUE THREAD

**Issue by 00travelgirl00** [pluginkollektiv/antivirus#36]
The label for the form is empty, which makes it hard for screen readers. 

We should add a text for the label.

**Comment by 00travelgirl00** [comment]
Patch: #37

**Comment by 00travelgirl00** [comment]
Patch was merged, so I close this ticket.

**Comment by krafit** [comment]
Closed in https://github.com/pluginkollektiv/antivirus/commit/08d6d04260312f7aa91db5ab56df5a65f8b572a7
