### ISSUE TITLE
test Antivirus with current WordPress Version 

### ISSUE THREAD

**Issue by 00travelgirl00** [pluginkollektiv/antivirus#39]
The Plugin has not be tested within the last 3 major releases of WordPress. Therefore we have a big warning in the plugin page:

"This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress."

**Comment by 2ndkauboy** [comment]
Fixing issue #41 and #42 I did some testing an from what I have experienced, it seems to work just fine with the latest WordPress version.
