### ISSUE TITLE
Check for Gutenberg compatibility

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/antivirus#40]
WordPress 5.0 will be here soon. Time for us to check, if our plugins are compatible with the Gutenberg Editor and WP 5.0 (a beta version is yet to be published). 

- [x] check (Gutenberg) editor with this plugin
- [x] check plugin settings site with active Gutenberg
- [x] fix potential issues
- [x] add `Tested up to: 5.0` to the plugins readme
- [x] publish changes as minor update or with upcoming plugin update

**Comment by 2ndkauboy** [comment]
Works with WordPress 5.0 and as it doesn't do anything with the editor, it also works with Gutenberg (integrated in WordPress 5.0). The theme check also successfully scans the latest version of TwentyNineteen.
