### ISSUE TITLE
Integrate Checksum Verifier

### ISSUE THREAD

**Issue by swissspidy** [pluginkollektiv/antivirus#5]
Checksum Verifier is a very helpful plugin, but only has 100+ downloads. Integrating it into Antivirus would make 100.000+ sites more safe.

This enhancement would make Antivirus more appealing for lots of users and would make Antivirus live up to its name. It would also mean that we'd stop supporting Checksum Verifier as a separate plugin and concentrate our efforts on Antivirus.

**Comment by glueckpress** [comment]
:100: Great idea!

**Comment by Zodiac1978** [comment]
+1

**Comment by stklcode** [comment]
Has finally been integrated in #56.
