### ISSUE TITLE
Test with WP 5.6

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/antivirus#70]
WordPress 5.6 will be here soon. Time for us to check, if our plugins are compatible 🥳

- [x] test with the current WP 5.6 RC
- [x] add `Tested up to: 5.6` to the plugins readme
- [x] publish changes as minor update or with upcoming plugin update

**Comment by stklcode** [comment]
Tested both 1.3.10 and latest 1.4.0-alpha against WP 5.6 RC1 on PHP 8.0.
Both versions don't seem to have any any issues, neither WP 5.6 nor PHP 8.0 or jQuery 3.

I'd vote for pushing forward to v1.4.0 instead of adding a 1.3.11 though.
