### ISSUE TITLE
Add option for Safebrowsing API key

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/antivirus#72]
We need to add an option for an own Safebrowsing API key, because we have hit the 10k limit and the plugin is starting to send out false positive emails.

I've asked Google for a higher limit but got no response. But I got a warning about the public available key.

We should make this an opt-in feature, like recommended here:
https://github.com/pluginkollektiv/antivirus/issues/42#issuecomment-464341420

**Comment by patrickrobrecht** [comment]
I've just merged #69 which restores the custom API key which got lost due to merge conflicts which were not resolved correctly.

**Comment by Zodiac1978** [comment]
So I can close this issue, correct?
